---
title: "Modeling Developmental Active XSL"
author: "George"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)
require(GGally)

source("R/helper.R")
source("R/fitting.R")
source("R/kachergis.R")
source("R/experiment_helpers.R")
```

## Load data

```{r load-data, eval=F}
# single-object exposure w frequency manipulation (mostly/all kids) - 
ad <- read_csv("data/act_data.csv") |>
  filter(!startsWith(trial_type, "fam")) |> # eliminate: fam-learning familiar-test
  rename(image1 = available_image1,
         image2 = available_image2,
         image3 = available_image3,
         image4 = available_image4,
         choice_label = choice_audio,
         test_label = test_audio) |>
  mutate(choice_image = sub("stims/", "", choice_image),
         image1 = sub("stims/", "", image1),
         image2 = sub("stims/", "", image2),
         image3 = sub("stims/", "", image3),
         image4 = sub("stims/", "", image4),
         target_image = sub("stims/", "", target_image),
         foil_image = sub("stims/", "", foil_image),
         test_label = sub("stims/", "", test_label)) |>
  mutate(label1 = choice_label)
# is_right will be added 

save(ad, file="data/act_data_preprocessed.Rdata")

# cross-situational;
# Martin's adding another 110 adults - which have randomImage1 and randomImage2 for passive condition (where they didn't get to make a selection)
xd <- read_csv("data/crossact_data.csv") |> 
  filter(!startsWith(trial_type, "fam")) |>
  mutate(choice_image = sub("stims/", "", choice_image),
         target_image = sub("stims/", "", target_image),
         target_label = sub("stims/find_", "", sub(".m4a", "", target_label)),
         image1 = sub("stims/", "", image1),
         image2 = sub("stims/", "", image2),
         image3 = sub("stims/", "", image3),
         image4 = sub("stims/", "", image4), 
         image5 = sub("stims/", "", image5), 
         image6 = sub("stims/", "", image6), 
         image7 = sub("stims/", "", image7), 
         image8 = sub("stims/", "", image8),
         random_image = sub("stims/", "", random_image))
# eliminate: fam-learning  fam-selection  fam-test (task familiarization trials)
xd_code <- read_csv("data/Crossact_codebook.csv")
# Note: label1 label2 give the order of the labels, not the 'correct' label-image

save(xd, xd_code, file="data/cross_act_preprocessed.Rdata")
```

```{r load-cross-act-data}
load("data/act_data_preprocessed.Rdata") # ad
load("data/cross_act_preprocessed.Rdata")

xd |> group_by(subject, experiment_name, age_group) |>
  summarise(n = n()) |>
  group_by(experiment_name, age_group) |>
  summarise(n = n())
```


## Examine training

```{r act-data, eval=F}
ad_s <- ad |> filter(subject=="p101")
table(ad_s$trial_type)
# learning          test 
#       16            16 

#ad_fam_train <- ad |> filter(trial_type=="fam-learning") # trial_index 1-4
# available_image1 - 4
#ad_fam_train |> select(starts_with('available_image')) # always bear cow penguin pig? 
#ad_fam_test <- ad |> filter(trial_type=="familiar-test") # trial_index 5-6
# choice_image, target_image, foil_image


ad_learn <- ad |> filter(trial_type=="learning")
ad_test <- ad |> filter(trial_type=="test") # trial_index 15-22, 31-38
# choice_image, target_image, foil_image  (2AFC) -- and test_audio

get_experiment_cooc_matrix(ad, "1") 
get_experiment_cooc_matrix(ad, "2A") # exposure phase: choice_image and choice_audio <- passive (not active)
get_experiment_cooc_matrix(ad, "2B") # ""
get_experiment_cooc_matrix(ad, "2C") # ""
```


```{r, echo=FALSE}
exp1_mat <- get_experiment_cooc_matrix(xd, "Experiment 1", iterations=24) 
heatmap(exp1_mat, scale="none")

expS1_mat <- get_experiment_cooc_matrix(xd, "Experiment S1", iterations=24) 
heatmap(expS1_mat)

exp2_mat <- get_experiment_cooc_matrix(xd, "Experiment 2", iterations=24) 
heatmap(exp2_mat)

exp3_mat <- get_experiment_cooc_matrix(xd, "Experiment 3", iterations=24) 
heatmap(exp3_mat)
```

# Cross-situational

(this may be the target of the CogSci paper)

```{r}
# unique(xd$experiment_name)
# "Experiment 2"  - all completely unfamiliar items, but fewer (6 instead of 12) - no systematic choices for kids
# "Experiment 3"  - has mutual exclusivity trials
# "Experiment 1"  "Experiment S1" - have a randomly-selected XSL trial after selection?
# randomized trial order - so use subject-specific training 

xd_test <- xd |> filter(trial_type=="test") |>  # | trial_type=="fam-test"
  rename(correct = is_right)

xd_test |> group_by(experiment_name, trial_type, age_group) |>
  summarise(correct = mean(correct)) |>
  ggplot(aes(x=age_group, y=correct, color=trial_type)) +
  facet_wrap(. ~ experiment_name) + 
  geom_point() + ylim(0,1)

# adult test: 8AFC
# kids test: 6AFC - in expt2, all 6 options are novel
# - expt 3: 4 are novel, 2 are familiar

# remove all fam- trials -- these are task familiarization trials with known objects
xd_s <- xd |> filter(subject=="Crossact1_p101", !startsWith(trial_type, "fam"))
table(xd_s$trial_type) # 19 trials
# learning     selection          test 
#       9             4             6 


# on trial_type=="selection", model should only learn choice_label -> choice_image
# (on selection trials, image1 - image6 / image8 (adults) encode the available options)

crossact_mats = list()
crossact_mats[["Experiment 1"]] <- get_experiment_cooc_matrix(xd, "Experiment 1")
crossact_mats[["Experiment 2"]] <- get_experiment_cooc_matrix(xd, "Experiment 2")
crossact_mats[["Experiment 3"]] <- get_experiment_cooc_matrix(xd, "Experiment 3")
crossact_mats[["Experiment S1"]] <- get_experiment_cooc_matrix(xd, "Experiment S1")

# in expt 3: 4 words are novel, 2 are familiar (pig, dog) -- need to be given strong associations
crossact_mats[["Experiment 3"]]["dog","dog.png"] = 100
crossact_mats[["Experiment 3"]]["pig","pig.png"] = 100

# empty matrices for each expt -- actually all the same?

# iterate over trials, handle training and selection/test trials
run_subject_trials(xd_s)

# Exp 3
xd_s <- xd |> filter(subject=="Crossact2_p101", !startsWith(trial_type, "fam"))
run_subject_trials(xd_s)
```


```{r fitting}
#ord <- get_subject_trial_ordering(xd_s)

# run model
#model(c(1,1,1), ords[[1]])

#compare_selection_rule_to_subject_matrix <- function()

# tests a model for one subject
test_run_model_per_subject <- function() {
  s = names(ords)[[1]]
  source("R/baseline.R") # source("R/kachergis.R")
  res <- model(c(), ords[[1]], start_matrix = crossact_mats$`Experiment 2`)
}

test_run_model_exp3 <- function() {
  s = "Crossact2_p101"
  source("R/baseline.R") # source("R/kachergis.R")
  res <- model(c(), ords[[s]], start_matrix = crossact_mats$`Experiment 3`)
}
# right now, this evaluates selection strategies - 
# want to jointly evaluate selection strategy + accuracy, given particular model (and parameters)


ords <- list()
for(s in unique(xd$subject)) {
  ords[[s]] <- get_subject_trial_ordering(xd |> filter(subject==s))
}

eval_selection_trials_group(ords, xd, "entropy") # 1235.1
eval_selection_trials_group(ords, xd, "confirmatory") # 1253.7 
eval_selection_trials_group(ords, xd, "random") # 1221.0 
eval_selection_trials_group(ords, xd, "novelty") # 1232.5 
eval_selection_trials_group(ords, xd, "margin") # 2681.2 - think through logic? 'object-perspective is correct'
```

```{r}
strategies = c("entropy", "confirmatory", "random", "novelty", "margin")

strategy_comparison = map_dfr(strategies, function(strat) {
  result = eval_selection_trials_group(ords, xd, strat)
  tibble(
    strategy = strat,
    total_nlogLik = result$total_nlogLik,
    mean_nlogLik = result$mean_nlogLik,
    n_selections = result$n_selections
  )
})

# Visualize
ggplot(strategy_comparison, aes(x = reorder(strategy, -mean_nlogLik), 
                                y = mean_nlogLik)) +
  geom_col(fill = "steelblue") +
  labs(title = "Selection strategy model comparison",
       subtitle = "Lower is better fit to human choices",
       x = "Strategy",
       y = "Mean Negative Log-Likelihood per Selection") +
  theme_classic() +
  coord_flip()
```

```{r}
# Do children and adults use different strategies?
age_strategy_comparison <- expand_grid(
  age_group = c("kids", "adults"),
  strategy = strategies
) |>
  mutate(
    result = map2(age_group, strategy, function(ag, strat) {
      # Filter subjects for this age group
      subjects_in_group <- xd |> 
        filter(age_group == ag) |> 
        pull(subject) |> 
        unique()
      
      # Subset ords and xd
      ords_subset <- ords[subjects_in_group]
      xd_subset <- xd |> filter(age_group == ag)
      
      # Evaluate strategy
      eval_selection_trials_group(ords_subset, xd_subset, strat)
    })
  ) |>
  unnest_wider(result)

# Visualize developmental differences
ggplot(age_strategy_comparison, aes(x = strategy, y = mean_nlogLik, 
                                    fill = age_group)) +
  geom_col(position = "dodge") +
  labs(title = "Selection strategies by age group") +
  theme_classic() +
  coord_flip()
```


```{r}
# Evaluate all strategies for each participant
evaluate_subject_strategies <- function(subject_id, ords, xd, strategies) {
  selections <- xd |> filter(subject == subject_id, trial_type == "selection")
  if(nrow(selections) == 0) return(NULL)
  
  # Get experiment name to use correct starting matrix
  expt_name <- xd |> filter(subject == subject_id) |> 
    pull(experiment_name) |> first()
  
  # Start with experiment-specific matrix, THEN add training
  mat <- crossact_mats[[expt_name]]
  training_mat <- create_cooc_matrix(ords[[subject_id]])
  mat <- mat + training_mat  # Combine priors with training
  
  # Evaluate each strategy
  results <- map_dfr(strategies, function(strat) {
    sel_result <- eval_selection_strategy(mat, selections, strategy = strat)
    
    tibble(
      subject = subject_id,
      strategy = strat,
      nlogLik = sel_result$nlogLik,
      mean_prob = sel_result$mean_prob,
      n_selections = nrow(selections)
    )
  })
  
  return(results)
}

# Apply to all subjects
strategies <- c("entropy", "confirmatory", "random", "novelty", "margin")

subject_strategy_fits <- map_dfr(names(ords), function(subj) {
  evaluate_subject_strategies(subj, ords, xd, strategies)
})

# Add subject metadata
subject_strategy_fits <- subject_strategy_fits |>
  left_join(
    xd |> 
      group_by(subject) |> 
      summarise(
        experiment_name = first(experiment_name),
        age_group = first(age_group),
        age = first(age)
      ),
    by = "subject"
  )

# Find best-fitting strategy for each subject
best_strategies <- subject_strategy_fits |>
  group_by(subject) |>
  slice_min(nlogLik, n = 1) |>
  ungroup()

# FixMe: looks like an odd scoring issue for Exp3 - all kids have the same nLogLik:
# (and look confirmatory) - is this related to the familiar items during training? 
# (we should make those have strong prior associations, rather than learned)

# Likelihood ratio tests for model comparison
subject_strategy_fits <- subject_strategy_fits |>
  group_by(subject) |>
  mutate(
    best_nlogLik = min(nlogLik),
    LR = -2 * (nlogLik - best_nlogLik), 
    p_value = pchisq(LR, df = 0, lower.tail = FALSE)  # df=0 for non-nested
  )

subject_strategy_fits |> ggplot(aes(x=strategy, y=LR)) + geom_boxplot()

best_strategies |> write_csv("data/likely_selection_strategy.csv")
subject_strategy_fits |> write_csv("data/subject_strategy_fits.csv")
```


```{r}
fit_model_per_subject <- function(model_name, xd, lower, upper, par_priors=NULL) {
  source(paste0("R/",model_name,".R"))
  
  ords <- list()
  for(s in unique(xd$subject)) {
    ords[[s]] <- get_subject_trial_ordering(xd |> filter(subject==s))
  }
  
  # sapply across subjects, save best-fitting parameters, log-liks, and per-subj/-item predictions
  sfits <- tibble()
  fit_results <- tibble()
  for(s in names(ords)) { # s = "p621758"
    xd_s <- xd |> filter(subject==s)
    testdat <- xd_s |> filter(trial_type=="test", trial_index<37) # excludes 37-44; Experiment S1's post-sampling phase test trials
    fit <- DEoptim::DEoptim(eval_model, lower=lower, upper=upper, par_priors=par_priors,
                          DEoptim::DEoptim.control(reltol=.001, NP=100, itermax=100),
                          ord = ords[[s]], testdat=testdat, logLik_only=T, # SSE_only=T
                          start_matrix = crossact_mats[[xd_s$experiment_name[1]]]) 
    # re-eval best fit
    best_par <- fit$optim$bestmem
    new_fit <- tibble(subject = s, neg_log_lik = fit$optim$bestval, chi = best_par[1], lambda = best_par[2], alpha = best_par[3])
    print(new_fit)
    sfits <- sfits |> bind_rows(new_fit)
    best_result <- eval_model(best_par, testdat, ords[[s]], crossact_mats[[xd_s$experiment_name[1]]])
    fit_results <- fit_results |> bind_rows(best_result)
  }
  return(list(sfits=sfits, fit_results=fit_results))
}

# test function - for crossact, it's all-AFC for adults and kids; need to do 2AFC version for act exp
eval_model <- function(parms, testdat, ord, start_matrix, SSE_only=FALSE, logLik_only=FALSE, par_priors = NULL) {
  res <- model(parms, ord = ord, start_matrix = start_matrix)
  mat <- res$matrix[testdat$target_label, testdat$target_image] # reorder matrix by correct mapping
  mod_perf = tibble(target_label = rownames(mat), mod_perf = diag(mat) / rowSums(mat))
  mp <- testdat |> left_join(mod_perf, by="target_label") |>
    select(subject, experiment_name, age_group, age, trial_index, choice_label, target_image, target_label, is_right, mod_perf) 
  logLik_value = -sum(mp$is_right * log(mp$mod_perf) + (1-mp$is_right) * log(1-mp$mod_perf)) 
  if (!is.null(par_priors)) {
    penalty <- sum(.004*(parms - par_priors)^2) # weak Gaussian regularization (penalize deviation from priors)
    logLik_value <- logLik_value + penalty
  }
  if(SSE_only) return(sum((mp$is_right - mp$mod_perf)^2)) # minimize SSE
  if(logLik_only) return(logLik_value) # minimize negative log-lik
  return(mp)
}

# "Crossact1_p121" (Exp 2) - Error in res$matrix[testdat$target_label, testdat$target_image] : 
#  subscript out of bounds
# the images in trial 24 are all NA...

# correct mapping is randomized per subject (just same structure) 

```


```{r, eval=F}
exp1_fit <- fit_model_to_group("kachergis", "Experiment 1", xd |> filter(subject!="Crossact1_p121"), 
                                  lower=c(.001, .01, .5), upper=c(3, 12, 1))
# logLik = 171.4043 parms = c(0.032338, 3.435991, 0.895025)
exp2_fit <- fit_model_to_group("kachergis", "Experiment 2", xd |> filter(subject!="Crossact1_p121"), 
                                  lower=c(.001, .01, .5), upper=c(3, 12, 1))
# logLik = 159.697490 parms = c(0.036741, 2.679146, 1.000000) 
# same LL with lambda = 3.021478, 1.453844, 7.052054, 10.207910, 0.979101 ...
exp3_fit <- fit_model_to_group("kachergis", "Experiment 3", xd |> filter(subject!="Crossact1_p121"), 
                                  lower=c(.001, .01, .5), upper=c(3, 12, 1))
# logLik = 202.944558 parms = c(0.002033, 0.355762, 0.500000)
expS1_fit <- fit_model_to_group("kachergis", "Experiment S1", xd |> filter(subject!="Crossact1_p121"), 
                                  lower=c(.001, .01, .5), upper=c(3, 12, 1))
# logLik = 275.737849 parms = c(0.176909, 2.241018, 0.961075)

save(exp1_fit, exp2_fit, exp3_fit, expS1_fit, file="data/exp_fits_kachergis.Rdata")

# fit individuals with exp1 group par priors:
ind_fits <- fit_model_per_subject("kachergis", xd |> filter(subject!="Crossact1_p121"), 
                                  lower=c(.001, .01, .5), upper=c(3, 12, 1), 
                                  par_priors = exp1_fit) # c(0.03233805, 3.43599139, 0.89502461)
save(ind_fits, file="data/ind_fits_kachergis_exp1_group_regularized.Rdata")
cor.test(ind_fits$sfits$chi, ind_fits$sfits$lambda) # -.32
cor.test(ind_fits$sfits$chi, ind_fits$sfits$alpha) # -.21
cor.test(ind_fits$sfits$alpha, ind_fits$sfits$lambda) # -.21

exp1_str_fit <- fit_model_to_group("strength", "Experiment 1", xd |> filter(subject!="Crossact1_p121"), 
                                  lower=c(.001, .5), upper=c(3, 1))
# logLik = 172.430055 parms = c(0.058560, 0.934179)
exp1_nov_fit <- fit_model_to_group("novelty", "Experiment 1", xd |> filter(subject!="Crossact1_p121"), 
                                  lower=c(.001, .01, .5), upper=c(3, 12, 1))
# logLik = 171.703926 parms = c(0.125845, 3.202186, 1.0)
save(exp1_str_fit, exp1_nov_fit, file="data/exp1_str_nov_fits.Rdata")


str_fits_reg <- fit_model_per_subject("strength", xd |> filter(subject!="Crossact1_p121"), 
                                  lower=c(.001, .5), upper=c(3, 1), 
                                  par_priors = exp1_str_fit) # c(0.058560, 0.934179)
nov_fits_reg <- fit_model_per_subject("novelty", xd |> filter(subject!="Crossact1_p121"), 
                                  lower=c(.001, .01, .5), upper=c(3, 12, 1), 
                                  par_priors = exp1_nov_fit) # c(0.125845, 3.202186, 1.0)
save(str_fits_reg, nov_fits_reg, file="data/ind_fits_str_nov_exp1_group_regularized.Rdata")
cor.test(str_fits_reg$sfits$chi, str_fits_reg$sfits$lambda) # -.34 (but lambda is actually alpha)

cor.test(nov_fits_reg$sfits$chi, nov_fits_reg$sfits$lambda) # -.09 n.s.
cor.test(nov_fits_reg$sfits$chi, nov_fits_reg$sfits$alpha) # -.36
cor.test(nov_fits_reg$sfits$alpha, nov_fits_reg$sfits$lambda) # .13 n.s.

sum(nov_fits_reg$sfits$neg_log_lik) # 556.23
sum(str_fits_reg$sfits$neg_log_lik) # 561.78

# fit individuals with no priors:
ind_fits <- fit_model_per_subject("rescorla-wagner", xd |> filter(subject!="Crossact1_p121"), 
                                  lower=c(.001, .001, .01), upper=c(1, 1, 2))
save(ind_fits, file="data/ind_fits_rescorla-wagner.Rdata")

ind_fits <- fit_model_per_subject("kachergis", xd |> filter(subject!="Crossact1_p121"), 
                                  lower=c(.001, .01, .5), upper=c(3, 12, 1))
# Experiment S1 has 2 test trials for each target_label and target_image -- should we only compare the first one to the model? or average people's two responses? -- trials 37-44 are a second test after the sampling phase, so we should save those for when we're modeling sampling
save(ind_fits, file="data/ind_fits_kachergis.Rdata")
mean(ind_fits$sfits$neg_log_lik) # 2.72 wo selection, 2.50 with selection!

ind_fits <- fit_model_per_subject("strength", xd |> filter(subject!="Crossact1_p121"), 
                                  lower=c(.001, .5), upper=c(1, 1))
save(ind_fits, file="data/ind_fits_strength.Rdata")
mean(ind_fits$sfits$neg_log_lik) # wo selection: 2.95 (lambda column contains alpha; there is no lambda in strength model)
# w selection: 2.69

ind_fits1 <- fit_model_per_subject("kachergis", xd |> filter(subject!="Crossact1_p121"), 
                                  lower=c(.001, .01, .5), upper=c(1, 12, 1))
save(ind_fits1, file="data/ind_fits_kachergis_chi1.Rdata")
mean(ind_fits1$sfits$neg_log_lik) # 2.71 - slightly better fit with more constrained chi
# 2.508 w selection trials

ind_fits <- fit_model_per_subject("kachergis", xd |> filter(subject!="Crossact1_p121"), 
                                  lower=c(.001, .01, .9), upper=c(3, 12, 1))
save(ind_fits, file="data/ind_fits_kachergis_alpha_p9-1.Rdata")
mean(ind_fits$sfits$neg_log_lik) # 2.98
cor(ind_fits$sfits |> select(-subject))

ind_fits <- fit_model_per_subject("novelty", xd |> filter(subject!="Crossact1_p121"), 
                                  lower=c(.001, .01, .5), upper=c(1, 12, 1))
save(ind_fits, file="data/ind_fits_novelty_chi1.Rdata")
mean(ind_fits$sfits$neg_log_lik) # 2.91 wo selection, 2.64 with selection trials


# group pars: $\chi=0.0323$, $\lambda=3.436$, and $\alpha=0.895$
ind_fits <- fit_model_per_subject("kachergis", xd |> filter(subject!="Crossact1_p121"), 
                                  lower=c(.001, .01, .5), upper=c(1, 12, 1), 
                                  par_priors = c(0.0323, 3.436, 0.895))
save(ind_fits, file="data/ind_fits_kachergis_regularized.Rdata")
mean(ind_fits$sfits$neg_log_lik) # 2.76
# selection: 2.55

ind_fits <- fit_model_per_subject("kachergis_reparam", xd |> 
                                    filter(subject!="Crossact1_p121", subject!="Crossact2_p101"),  
                                  lower=c(.01, .01, .1), upper=c(.5, 0.99, 1))
save(ind_fits, file="data/ind_fits_kachergis_reparam.Rdata")
mean(ind_fits$sfits$neg_log_lik) # 3.52


ind_fits <- fit_model_per_subject("uncertainty", xd |> filter(subject!="Crossact1_p121"),  
                                  lower=c(.001, .01, .5), upper=c(1, 12, 1))
save(ind_fits, file="data/ind_fits_uncertainty.Rdata")
mean(ind_fits$sfits$neg_log_lik) # 2.20
```


```{r}
load("data/ind_fits_uncertainty.Rdata") # 
load("data/ind_fits_kachergis_chi1.Rdata") # chi constrained to 0-1
xx <- ind_fits$sfits |> left_join(ind_fits1$sfits, by="subject")
# .x = unconstrained, .y = constrained
xx |> ggplot(aes(x=neg_log_lik.x, y=neg_log_lik.y)) + geom_point()
xx |> ggplot(aes(x=chi.x, y=chi.y)) + geom_point()
xx |> ggplot(aes(x=lambda.x, y=lambda.y)) + geom_point()
xx |> ggplot(aes(x=alpha.x, y=alpha.y)) + geom_point()

#load("data/ind_fits_kachergis_alpha_p9-1.Rdata") # alpha constrained to 0.9 - 1.0
```

```{r}
results <- ind_fits1$fit_results |> 
  mutate(age_years = ifelse(age<18, round(age), "adult"),
         age_years = ifelse(is.na(age_years), "adult", age_years),
         adult = ifelse(age_years=="adult", 1, 0)) |> # 1 adult had NA age
  group_by(experiment_name, age_years, adult, subject, age) |>
  summarise(Human = mean(is_right),
            Model = mean(mod_perf)) |>
  left_join(ind_fits1$sfits) 

results |>
  group_by(experiment_name, age_years) |>
  summarise(hum_sd = sd(Human), 
            mod_sd = sd(Model),
            Human = mean(Human),
            Model = mean(Model)) |>
  pivot_longer(cols = c(Human, Model), names_to = "group", values_to = "Accuracy") |>
  ggplot(aes(x=age_years, y=Accuracy, color=group, shape=group)) + 
  facet_wrap(. ~ experiment_name) +
  geom_point() + # geom_linerange(aes(ymin = )) + 
  theme_classic() +
  ylim(0,1) + geom_hline(yintercept=1/8, linetype='dashed')
```

```{r}
library(fpc)
library(factoextra)

param_df <- results |> ungroup() |>
  select(chi, lambda, alpha) |>
  scale()

pk <- pamk(param_df)
# Medoids:
# pk$pamobject$medoids
results[pk$pamobject$id.med,]

results$cluster <- pk$pamobject$clustering

#table(pk$pamobject$clustering) # 8 clusters
#  1  2  3  4  5  6  7  8 
# 15 29 36 40 16  8 22 24 
```




```{r}
results |>
  group_by(cluster) |>
  summarise(n = n(),
            age = mean(age, na.rm=T),
            prop_adult = mean(adult, na.rm=T),
            lambda = mean(lambda),
            alpha = mean(alpha),
            chi = mean(chi), 
            Human = mean(Human),
            Model = mean(Model),
            neg_log_lik = mean(neg_log_lik)) |>
  arrange(desc(Human))
```

```{r}
t.test(results |> filter(adult==1) |> pull(chi),
       results |> filter(adult==0) |> pull(chi)) # adults 0.45, kids 0.25 p=.002

t.test(results |> filter(adult==1) |> pull(alpha),
       results |> filter(adult==0) |> pull(alpha)) # n.s.

t.test(results |> filter(adult==1) |> pull(lambda),
       results |> filter(adult==0) |> pull(lambda)) # adults = 6.38, kids = 4.77

cor.test(results$Model, results$lambda) # r=0.17 p=.02
cor.test(results$Model, results$alpha) # r=-.62
cor.test(results$Model, results$chi) # r=0.68
```


```{r}
# Do different "learning styles" show different sampling patterns?
results |>
  ggplot(aes(x = factor(cluster), y = Human)) +
  geom_boxplot() + geom_point(aes(color = age)) + theme_classic()
```


Look at parameters by age and performance.

```{r, fig.width=8, fig.height=8}
#require(GGally)
#ggpairs(results[,c("Human","Model","chi","lambda","alpha","neg_log_lik")]) # "age",

require(corrplot)
corrplot(results |> ungroup() |>
           filter(subject!="p745776") |> select(Human,Model,chi,lambda,alpha,neg_log_lik)) # "age"
```

```{r}
require(rgl)

col_palette <- colorRampPalette(c("blue", "red"))(10)
plot3d( 
  x=results$chi, y=results$lambda, z=results$alpha, 
  colvar = results$Human, col = col_palette, 
  type = 'p', size = 5,
  xlab="chi", ylab="lambda", zlab="alpha")


#require(car)
#scatter3d( 
#  x=results$chi, y=results$lambda, z=results$alpha, 
#  colvar = results$Human, col = col_palette, 
#  type = 'p', size = 5, xlab="chi", ylab="lambda", zlab="alpha", colkey=TRUE)

htmlwidgets::saveWidget(rglwidget(width = 520, height = 520), 
                        file = "HtmlWidget/3d-params.html",
                        libdir = "libs",
                        selfcontained = FALSE
                        )
```


```{r}
cor.test(results$age, results$chi) # .24 (stronger relation than age vs. performance)
cor.test(results$age, results$lambda) # .19 # older -> greater focus on uncertainty (and thus sampling of ambiguous refs)
cor.test(results$age, results$alpha) # .02 - n.s.
cor.test(results$age, results$Human) # .23

cor.test(results$Human, results$lambda) # .15 p=.04
cor.test(results$Human, results$chi) # .65 p<.001
cor.test(results$Human, results$alpha) # -.46

cor.test(results$age, results$neg_log_lik) # n.s.
```


## Relationships between model parameters and performance

```{r}
library(lme4)

results_clean <- results |>
  filter(!is.na(age)) |>
  mutate(age_centered = scale(age, center = TRUE, scale = FALSE))

# Does chi predict performance above and beyond age?
m1 <- lmer(Human ~ age_centered + (1|experiment_name), data = results_clean)
m2 <- lmer(Human ~ age_centered + chi + (1|experiment_name), data = results_clean)
m3 <- lmer(Human ~ age_centered + chi + lambda + (1|experiment_name), data = results_clean)
m4 <- lmer(Human ~ age_centered + chi + lambda + alpha + (1|experiment_name), data = results_clean)

anova(m1, m2, m3, m4)
```


```{r}
# Does lambda predict performance above and beyond age?
m1 <- lmer(Human ~ age_centered + (1|experiment_name), data = results_clean)
m2 <- lmer(Human ~ age_centered + lambda + (1|experiment_name), data = results_clean)
m3 <- lmer(Human ~ age_centered + lambda + chi + (1|experiment_name), data = results_clean)
m4 <- lmer(Human ~ age_centered + lambda + chi + alpha + (1|experiment_name), data = results_clean)

anova(m1, m2, m3, m4)
```

```{r}
results_clean |>
  mutate(age_group = cut(age, breaks = c(0, 5, 7, 100), 
                         labels = c("3-5 years", "5-7 years", "Adults"))) |>
  ggplot(aes(x=age_group, y=lambda)) +
  geom_violin() + geom_point(alpha = 0.6) +
  labs(x = "Age group", 
       y = "Lambda (uncertainty vs. familiarity focus)") +
  theme_classic()
```


```{r}
results_clean |>
  mutate(age_group = cut(age, breaks = c(0, 5, 7, 100), 
                         labels = c("3-5 years", "5-7 years", "Adults"))) |>
  ggplot(aes(x = chi, y = Human, color = age_group)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Chi (learning rate)", 
       y = "Test Accuracy") +
  theme_classic()
```



## Sampling behavior analysis

Need to extract relative entropy for each chosen referent on selection trials.

```{r}
# Extract sampling data
sampling_data <- xd |>
  filter(trial_type == "selection") |>
  left_join(results |> select(subject, chi, lambda, alpha, Human, age))

# Create ambiguity scores based on model predictions
# For each selection trial, calculate entropy of chosen vs. unchosen items

get_selection_ambiguity <- function(subject_id, selection_trial_idx, ords, parms) {
  #ord <- ords[[subject_id]]
  xd_s <- xd |> filter(subject == subject_id) # and experiment?
  ord <- get_subject_trial_ordering(xd_s)
  # Run model up to selection point
  res <- model(parms, ord = ord, iterations = selection_trial_idx - 1,
               start_matrix = crossact_mats[[xd |> filter(subject==subject_id) |>
                                              pull(experiment_name) |> first()]])
  
  # Calculate entropy for each available referent
  mat <- res$matrix
  entropies <- apply(mat, 2, shannon.entropy)
  
  # Get actual choice
  choice_img <- xd |> 
    filter(subject == subject_id, trial_index == selection_trial_idx) |>
    pull(choice_image)
  
  return(list(
    choice_entropy = entropies[choice_img],
    mean_entropy = mean(entropies),
    max_entropy = max(entropies),
    chose_max = choice_img == names(which.max(entropies))
  ))
}

# Apply to all subjects and selection trials
sampling_analysis <- sampling_data |>
  group_by(subject) |>
  mutate(selection_num = row_number()) |>
  rowwise() |>
  mutate(
    # This requires fitting - use best-fit params from ind_fits
    parms = list(ind_fits$sfits |> filter(subject == !!subject) |> 
                  select(chi, lambda, alpha) |> as.numeric())
  )
```

## Selection Strategy Evaluation

```{r}
# Evaluate each strategy for each age group
selection_strategies <- c("entropy", "confirmatory", "random", "novelty", "margin")

strategy_fits <- expand_grid(
  experiment = unique(xd$experiment_name),
  age_group = c("child", "adult"),
  strategy = selection_strategies
) |>
  rowwise() |>
  mutate(
    nlogLik = eval_selection_trials_group(
      ords |> keep(~{
        subj <- names(ords)[which(names(ords) == .x)]
        exp_match <- xd |> filter(subject == subj) |> 
          pull(experiment_name) |> first() == experiment
        age_match <- xd |> filter(subject == subj) |>
          pull(age_group) |> first() == age_group
        exp_match & age_match
      }),
      xd |> filter(experiment_name == experiment, age_group == age_group),
      strategy = strategy
    )
  )

# Visualize best-fitting strategies by age/experiment
strategy_fits |>
  ggplot(aes(x = age_group, y = -nlogLik, fill = strategy)) +
  geom_col(position = "dodge") +
  facet_wrap(~experiment) +
  labs(title = "Selection strategy fits by age and experiment",
       y = "Log Likelihood") +
  theme_classic()
```

